### ISSUE TITLE
Node.js 6 support?

### ISSUE THREAD

**Issue by g-plane** [sindresorhus/delay-cli#1]
`async/await` requires Node.js 7.6 at least. So using `async/await` will be broken in Node.js 6.

**Comment by skvggor** [comment]
@g-plane , 

In `package.json`:

```json
"engines": {
  "node": ">=8"
}
```

Maybe the plan was not to give this support 😢 .

**Comment by sindresorhus** [comment]
I only support Node.js 8 for new CLIs I make. There's no good reason not to be on latest Node.js version on your own computer. Servers are different though.
