### ISSUE TITLE
JavaScript Module

### ISSUE THREAD

**Issue by dawadam** [sindresorhus/delay-cli#3]
A JavaScript module would be handy

**Comment by sindresorhus** [comment]
It's mentioned in the readme: https://github.com/sindresorhus/delay-cli#related

**Comment by dawadam** [comment]
The solution is to use : sindresorhus/delay

**Comment by dawadam** [comment]
But, delay can not be compiled with webpack.

    ERROR in static/js/vendor.89636e1f22f21e16218a.js from UglifyJs
    Unexpected token: operator (>) [./~/delay/index.js:3,0]
